# Site Settings
baseurl: ""
url : "https://butt3r.github.io/"

# Blog Settings
theme_settings :
  title : MOONCAKE
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/grape.png
    username : BUTTER
    description : To  boldly  go  where  no  one  has  gone  before.
    experience :
      - start : 2020-02-01
        end : ~
        experience : not yet
    skills : 
      - skill : UE4,  C/C++
        value : 10  # Percent value
        
  # Icons
  icons :
    email:  oos9596@gmail.com
    linkedin:  # Full URL 
    github: "https://github.com/Butt3r"
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
