name: SCRIPT¡ÆC
description: to boldly go
meta_description: " "

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: https://butt3r.github.io
google_analytics: " "
gems: [jekyll-paginate]

# Details for the RSS feed generator
url: https://butt3r.github.io
author: butt3r
