# site settings
title: SCRIPT5¡ÆC
subtitle: " "
email: " "
description: " "
baseurl: " "
url: "https://butt3r.github.io/"
author: butter
zip_code: 55555
country: Korea

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/Butt3r
gitlab_url: https://gitlab.com/u/andrewbanchich
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195

# build settings
markdown: kramdown

sass:
  style: compressed
